### ISSUE TITLE
📃Suggested-4Days-Plan #1

### ISSUE THREAD

**Issue by Saqibi4213** [Saqibi4213/space-travelers#1]
Day1: project initialization & project structure setup .
Day2: Redux store setup & routing setup .
Day3: component development .
Day4: finalization , integratory, reviewing, finalization, Kanban board management

**Comment by ahzamir** [comment]
@Saqibi4213 

- I can not see the design part, you also need to add some tasks for the mobile and desktop version designs and assign them to the responsible person for the exact part.

**Comment by ahzamir** [comment]
- Implement my feedback and start working on your project, you don't need to submit your Kanban Board again it's approved, good luck
