### ISSUE TITLE
🔧Reduxstore Reduxreducer & Reduxactions Set-up (group task)(4h) #5

### ISSUE THREAD

**Issue by Saqibi4213** [Saqibi4213/space-travelers#5]
The initial setup for Redux (Store, Reducer, and Actions) will be done as a group. ( group task)
This includes creating the main store file and setting up the basic structure for reducers and actions. (group task)
After the initial setup, each team member is responsible for adding their specific part to the Redux files (individually).

**Comment by ahzamir** [comment]
@Saqibi4213 

Creating the empty main redux files (Store, Actions, Reducers) and redux store should be done as a group, but the action and reducers everyone adds her part to the actions and reducers!

For example, my part is Mission so I need to add my state for the mission and the actions and reducers for changing and updating it to the redux files.
